[workspace]
resolver = "3"
members = ["crates/llimorse", "crates/llimorse-chat", "crates/term-ui", "crates/work-buddy"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
llimorse = { path = "crates/llimorse" }
llimorse-chat = { path = "crates/llimorse-chat" }
term-ui = { path = "crates/term-ui" }
anyhow = "1"
bytes = "1"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
reqwest = { version = "0.13", features = ["json", "stream"] }
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time"] }
tracing = "0.1"
