[package]
name = "llimo"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bytes = "1"
clap.workspace = true
futures.workspace = true
pin-project = "1"
reqwest = { version = "0.13", features = ["json", "stream"] }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
urlencoding = "2"
