[package]
name = "work-buddy"
version.workspace = true
edition = "2024"

[dependencies]
anyhow.workspace = true
chrono = "0.4"
clap.workspace = true
fastrand = "2"
helpers.workspace = true
llimorse.workspace = true
llimorse-chat.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
term-ui.workspace = true
tokio.workspace = true
toml = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
